name: Miri Memory Safety

on:
  workflow_dispatch:

permissions: read-all

jobs:
  miri:
    name: Miri Memory Safety
    runs-on: ubuntu-latest
    timeout-minutes: 300
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7
      - name: Setup Rust nightly
        uses: dtolnay/rust-toolchain@5b842231ba77f5c045dba54ac5560fed2db780e2 # nightly
        with:
          components: miri
      - name: Run Miri
        run: cargo miri test
        env:
          MIRIFLAGS: "-Zmiri-strict-provenance -Zmiri-disable-isolation"
