name: Spellcheck

on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main" ]

permissions: read-all

jobs:
  spellcheck:
    name: Documentation Spellcheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7
      - name: Setup Rust
        uses: dtolnay/rust-toolchain@29eef336d9b2848a0b548edc03f92a220660cdb8 # stable
      - name: Install cargo-spellcheck
        uses: taiki-e/install-action@682e7d9e49c5e653d371fc6adbda67653461378a # v2
        with:
          tool: cargo-spellcheck
      - name: Run spellcheck
        run: cargo spellcheck check || echo "Spellcheck finished with potential issues."
